### ISSUE TITLE
VS Code test is flaky

### ISSUE THREAD

**Issue by samestep** [quench-lang/quench#25]
These are the last 25 lines of output from the "Run tests" step in the `vscode` job of [this failed run](https://github.com/quench-lang/quench/pull/23/checks?check_run_id=2162497761) for 3d5398cb3b50d6adf1603214f802f11968f89ff4 (part of #23):
```
  Quench

    1) correctly reports syntax error(s) for "Hello, world!"

  0 passing (2s)

  1 failing

  1) Quench
       correctly reports syntax error(s) for "Hello, world!":
     Error: TextEditor#edit not possible on closed editors
  	at Object.edit (.vscode-test/vscode-linux-x64-1.54.3/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:49471)
  	at Context.<anonymous> (out/test/suite/extension.test.js:39:22)


No authentication provider 'github' is currently registered.

Settings Sync: Accounts are not initialized

Exit code:   1
Done

Failed
Failed to run tests.
Error: Process completed with exit code 1.
```
The failure corresponds to [line 44 of `editors/code/src/test/suite/extension.test.ts` from the same commit](https://github.com/quench-lang/quench/blob/3d5398cb3b50d6adf1603214f802f11968f89ff4/editors/code/src/test/suite/extension.test.ts#L44). My first thought was that this is a race condition caused by sleeping for a second on line 40, but commenting out line 40 doesn't do anything when I run the tests locally (they succeed), so I'm not sure exactly what this is.

**Comment by samestep** [comment]
The same failure happened again: https://github.com/quench-lang/quench/runs/2172247536
